services:
  xander:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # Uncomment below to use Unix socket files.
    # Note that socket files mapped via socat/ssh tunnels do not work when using containers on OS X.
    # volumes:
    #   - /your/path/to/cardano-node.socket:/tmp/cardano-node.socket

